### ISSUE TITLE
typo in defineComponents.lua

### ISSUE THREAD

**Issue by Nimblz** [AmaranthineCodices/recs#11]
There is a typo in defineComponents

https://github.com/AmaranthineCodices/recs/blob/c2026fd53746bd246fd20f7052a8f41d3dc8a7a4/src/defineComponent.lua#L33-L34

definition.defaultProps is never set, should be defaultProps and defaultProps()

**Comment by AmaranthineCodices** [comment]
closed in #14, I botched the commit message
